import { OrdersJournalPage, type OrdersJournalConfig } from "../components/OrdersJournalPage";

const CONFIG: OrdersJournalConfig = {
  kind: "K",
  title: "K-buyruqlar",
  subtitle: "Kadrlar bo'yicha buyruqlar (ishga qabul, o'tkazish, rag'batlantirish, intizomiy va boshqalar)",
  path: "/journals/k-buyruqlar",
  newLabel: "Yangi K-buyruq",
  categories: {
    hire: { label: "Qabul qilish", bg: "bg-[#ecfdf5]", text: "text-[#059669]" },
    transfer: { label: "O'tkazish", bg: "bg-[#f3e8ff]", text: "text-[#7c3aed]" },
    reward: { label: "Rag'batlantirish", bg: "bg-[#fff4e6]", text: "text-[#c2410c]" },
    discipline: { label: "Intizomiy", bg: "bg-[#fee2e2]", text: "text-[#dc2626]" },
    trip: { label: "Xizmat safari", bg: "bg-[#f3e8ff]", text: "text-[#7c3aed]" },
    terminate: { label: "Ishdan bo'shatish", bg: "bg-[#fee2e2]", text: "text-[#b91c1c]" },
    other: { label: "Boshqa", bg: "bg-slate-100", text: "text-slate-600" },
  },
  stats: {
    total: 248,
    done: 186,
    donePct: "75.0%",
    progress: 42,
    progressPct: "16.9%",
    cancelled: 8,
    cancelledPct: "3.2%",
    month: 18,
    monthDelta: 6,
    totalDelta: 14,
    archive: 420,
  },
  seed: [
    {
      id: "k1",
      number: "K-00124",
      date: "2025-01-12",
      subject: "Aliyev Behruzni ishga qabul qilish haqida",
      category: "hire",
      person: "Aliyev Behruz",
      department: "IT bo'limi",
      responsible: "HR Admin",
      status: "done",
      description: "Aliyev Behruz Alisherovichni 2025-yil 15-yanvardan IT bo'limiga dasturchi lavozimiga ishga qabul qilish.",
      history: [
        { at: "12.01.2025 10:20", text: "Buyruq yaratildi", by: "HR Admin" },
        { at: "12.01.2025 14:05", text: "Rektor tasdiqladi", by: "Qodirov A." },
      ],
      comments: [
        { at: "12.01.2025", by: "HR Admin", text: "Shartnoma nusxasi biriktirildi." },
        { at: "13.01.2025", by: "IT boshliq", text: "Ish joyi tayyor." },
        { at: "13.01.2025", by: "Aliyev B.", text: "Buyruq bilan tanishdim." },
      ],
    },
    {
      id: "k2",
      number: "K-00123",
      date: "2025-01-10",
      subject: "Karimova Dilnozani boshqa bo'limga o'tkazish",
      category: "transfer",
      person: "Karimova Dilnoza",
      department: "Kadrlar bo'limi",
      responsible: "HR Direktor",
      status: "progress",
      description: "Karimova Dilnoza Shavkatovnani Marketing bo'limidan Kadrlar bo'limiga o'tkazish.",
      history: [{ at: "10.01.2025 09:00", text: "Buyruq yaratildi", by: "HR Direktor" }],
      comments: [{ at: "10.01.2025", by: "HR Direktor", text: "Imzo kutilyapti." }],
    },
    {
      id: "k3",
      number: "K-00122",
      date: "2025-01-08",
      subject: "Yusupova Nilufarni rag'batlantirish to'g'risida",
      category: "reward",
      person: "Yusupova Nilufar",
      department: "Iqtisodiyot fakulteti",
      responsible: "Dekan",
      status: "done",
      description: "Yusupova Nilufar Rustamovnaga pul mukofoti berish haqida.",
      history: [{ at: "08.01.2025 11:30", text: "Buyruq imzolandi", by: "Rektor" }],
      comments: [],
    },
    {
      id: "k4",
      number: "K-00121",
      date: "2025-01-05",
      subject: "Toshmatov Bekzodga intizomiy jazo qo'llash",
      category: "discipline",
      person: "Toshmatov Bekzod",
      department: "IT bo'limi",
      responsible: "HR Admin",
      status: "cancelled",
      description: "Mehnat intizomini buzganligi uchun hayfsan e'lon qilish — keyinchalik bekor qilindi.",
      history: [
        { at: "05.01.2025 10:00", text: "Dalolatnoma kiritildi", by: "IT boshliq" },
        { at: "06.01.2025 12:00", text: "Bekor qilindi", by: "HR Direktor" },
      ],
      comments: [{ at: "06.01.2025", by: "HR Direktor", text: "Yozma ogohlantirish bilan cheklanishga qaror qilindi." }],
    },
    {
      id: "k5",
      number: "K-00120",
      date: "2024-12-28",
      subject: "Rahimova Dilnozani xizmat safariga yuborish",
      category: "trip",
      person: "Rahimova Dilnoza",
      department: "Xalqaro aloqalar",
      responsible: "Prorektor",
      status: "done",
      description: "2025-yil 5–12-yanvar kunlari Turkiyaga xizmat safari.",
      history: [{ at: "28.12.2024 14:00", text: "Buyruq tasdiqlandi", by: "Prorektor" }],
      comments: [],
    },
    {
      id: "k6",
      number: "K-00119",
      date: "2024-12-20",
      subject: "Ismoilova Malikani ishga qabul qilish haqida",
      category: "hire",
      person: "Ismoilova Malika",
      department: "Ingliz tili kafedrasi",
      responsible: "HR Admin",
      status: "progress",
      description: "Soatbay o'qituvchi sifatida ishga qabul qilish.",
      history: [{ at: "20.12.2024 12:15", text: "Buyruq yaratildi", by: "HR Admin" }],
      comments: [],
    },
    {
      id: "k7",
      number: "K-00118",
      date: "2024-12-15",
      subject: "Ergashev Javloni boshqa lavozimga o'tkazish",
      category: "transfer",
      person: "Ergashev Javlon",
      department: "Xalqaro aloqalar",
      responsible: "HR Direktor",
      status: "done",
      description: "Mutaxassisdan bo'lim mudiri o'rinbosariga o'tkazish.",
      history: [{ at: "15.12.2024 09:40", text: "Imzolandi", by: "Rektor" }],
      comments: [],
    },
    {
      id: "k8",
      number: "K-00117",
      date: "2024-12-01",
      subject: "Nazarova Kamolaga rag'batlantirish berish",
      category: "reward",
      person: "Nazarova Kamola",
      department: "Marketing bo'limi",
      responsible: "HR Admin",
      status: "done",
      description: "Yil yakunida eng yaxshi natija uchun mukofot.",
      history: [{ at: "01.12.2024 10:00", text: "Buyruq chiqarildi", by: "HR Admin" }],
      comments: [],
    },
    {
      id: "k9",
      number: "K-00116",
      date: "2024-11-18",
      subject: "Qosimov Sardorni ishdan bo'shatish haqida",
      category: "terminate",
      person: "Qosimov Sardor",
      department: "Moliya bo'limi",
      responsible: "HR Direktor",
      status: "done",
      description: "Mehnat shartnomasi muddati tugashi munosabati bilan.",
      history: [{ at: "18.11.2024 15:00", text: "Ijro etildi", by: "Rektor" }],
      comments: [],
    },
    {
      id: "k10",
      number: "K-00115",
      date: "2024-11-05",
      subject: "Abdullayeva Sevarani xizmat safariga yuborish",
      category: "trip",
      person: "Abdullayeva Sevara",
      department: "Agronomiya fakulteti",
      responsible: "Dekan",
      status: "progress",
      description: "Ilmiy konferensiyaga xizmat safari — 7 kun.",
      history: [{ at: "05.11.2024 09:00", text: "Jarayonda", by: "HR Admin" }],
      comments: [],
    },
  ],
};

export function KBuyruqlarPage() {
  return <OrdersJournalPage config={CONFIG} />;
}
