import { OrdersJournalPage, type OrdersJournalConfig } from "../components/OrdersJournalPage";

const CONFIG: OrdersJournalConfig = {
  kind: "N",
  title: "N-buyruqlar",
  subtitle: "Normativ va ichki buyruqlar (tartib, reglament, tashkiliy qarorlar va boshqalar)",
  path: "/journals/n-buyruqlar",
  newLabel: "Yangi N-buyruq",
  categories: {
    regulation: { label: "Reglament", bg: "bg-[#e8f1ff]", text: "text-[#1b5ef3]" },
    organization: { label: "Tashkiliy", bg: "bg-[#ecfdf5]", text: "text-[#059669]" },
    schedule: { label: "Jadval", bg: "bg-[#fff4e6]", text: "text-[#c2410c]" },
    commission: { label: "Komissiya", bg: "bg-[#f3e8ff]", text: "text-[#7c3aed]" },
    other: { label: "Boshqa", bg: "bg-slate-100", text: "text-slate-600" },
  },
  stats: {
    total: 132,
    done: 98,
    donePct: "74.2%",
    progress: 24,
    progressPct: "18.2%",
    cancelled: 4,
    cancelledPct: "3.0%",
    month: 9,
    monthDelta: 3,
    totalDelta: 8,
    archive: 210,
  },
  seed: [
    {
      id: "n1",
      number: "N-000089",
      date: "2025-01-14",
      subject: "Ichki mehnat tartibi qoidalarini tasdiqlash to'g'risida",
      category: "regulation",
      person: "HR Direktor",
      department: "Kadrlar bo'limi",
      responsible: "Rektor",
      status: "done",
      description: "Universitet ichki mehnat tartibi qoidalarining yangi tahririni tasdiqlash.",
      history: [
        { at: "12.01.2025 10:00", text: "Loyiha tayyorlandi", by: "HR Direktor" },
        { at: "14.01.2025 16:00", text: "Ijro etildi", by: "Rektor" },
      ],
      comments: [
        { at: "13.01.2025", by: "Yurist", text: "Huquqiy ekspertiza o'tkazildi." },
        { at: "14.01.2025", by: "HR Admin", text: "Bo'limlarga yetkazildi." },
        { at: "14.01.2025", by: "Rektor", text: "Tasdiqlandi." },
      ],
    },
    {
      id: "n2",
      number: "N-000088",
      date: "2025-01-11",
      subject: "Attestatsiya komissiyasi tarkibini tasdiqlash",
      category: "commission",
      person: "Prorektor",
      department: "O'quv bo'limi",
      responsible: "Rektor",
      status: "progress",
      description: "2025-yil attestatsiya komissiyasi a'zolarini tasdiqlash.",
      history: [{ at: "11.01.2025 11:00", text: "Jarayonda", by: "Prorektor" }],
      comments: [{ at: "11.01.2025", by: "Prorektor", text: "Nomzodlar ro'yxati kelishilmoqda." }],
    },
    {
      id: "n3",
      number: "N-000087",
      date: "2025-01-09",
      subject: "O'quv jarayoni jadvalini o'zgartirish haqida",
      category: "schedule",
      person: "O'quv bo'limi mudiri",
      department: "O'quv bo'limi",
      responsible: "Prorektor",
      status: "done",
      description: "Bahorgi semestr dars jadvaliga tuzatishlar kiritish.",
      history: [{ at: "09.01.2025 15:30", text: "Ijro etildi", by: "Prorektor" }],
      comments: [],
    },
    {
      id: "n4",
      number: "N-000086",
      date: "2025-01-06",
      subject: "Ish vaqti rejimini vaqtincha o'zgartirish",
      category: "organization",
      person: "HR Admin",
      department: "Kadrlar bo'limi",
      responsible: "Rektor",
      status: "cancelled",
      description: "Qishki ta'til davrida ish vaqtini qisqartirish — bekor qilindi.",
      history: [
        { at: "04.01.2025 09:00", text: "Buyruq yaratildi", by: "HR Admin" },
        { at: "06.01.2025 14:00", text: "Bekor qilindi", by: "Rektor" },
      ],
      comments: [{ at: "06.01.2025", by: "Rektor", text: "Avvalgi rejim saqlanadi." }],
    },
    {
      id: "n5",
      number: "N-000085",
      date: "2024-12-27",
      subject: "Hujjat aylanishi reglamentini tasdiqlash",
      category: "regulation",
      person: "Kantelyariya",
      department: "Kantelyariya",
      responsible: "Rektor",
      status: "done",
      description: "Elektron va qog'oz hujjat aylanishi tartibini yangilash.",
      history: [{ at: "27.12.2024 12:00", text: "Ijro etildi", by: "Rektor" }],
      comments: [],
    },
    {
      id: "n6",
      number: "N-000084",
      date: "2024-12-18",
      subject: "Tekshiruv komissiyasi tuzish to'g'risida",
      category: "commission",
      person: "Ichki audit",
      department: "Moliya bo'limi",
      responsible: "Rektor",
      status: "progress",
      description: "Inventarizatsiya bo'yicha vaqtinchalik komissiya tuzish.",
      history: [{ at: "18.12.2024 10:20", text: "Jarayonda", by: "HR Admin" }],
      comments: [],
    },
    {
      id: "n7",
      number: "N-000083",
      date: "2024-12-10",
      subject: "Kutubxona ish tartibini tasdiqlash",
      category: "organization",
      person: "Kutubxona mudiri",
      department: "Kutubxona",
      responsible: "Prorektor",
      status: "done",
      description: "Kutubxona ochiq vaqti va foydalanish qoidalarini yangilash.",
      history: [{ at: "10.12.2024 11:40", text: "Ijro etildi", by: "Prorektor" }],
      comments: [{ at: "10.12.2024", by: "Kutubxona mudiri", text: "E'lon doskasiga chiqarildi." }],
    },
    {
      id: "n8",
      number: "N-000082",
      date: "2024-11-28",
      subject: "Imtihon sessiyasi jadvalini tasdiqlash",
      category: "schedule",
      person: "O'quv bo'limi mudiri",
      department: "O'quv bo'limi",
      responsible: "Prorektor",
      status: "done",
      description: "Qishki imtihon sessiyasi jadvali.",
      history: [{ at: "28.11.2024 16:00", text: "Ijro etildi", by: "Prorektor" }],
      comments: [],
    },
    {
      id: "n9",
      number: "N-000081",
      date: "2024-11-15",
      subject: "Axborot xavfsizligi reglamentini yangilash",
      category: "regulation",
      person: "IT boshliq",
      department: "IT bo'limi",
      responsible: "Rektor",
      status: "done",
      description: "Parol siyosati va ma'lumotlarga kirish tartibini yangilash.",
      history: [{ at: "15.11.2024 14:00", text: "Ijro etildi", by: "Rektor" }],
      comments: [],
    },
    {
      id: "n10",
      number: "N-000080",
      date: "2024-11-02",
      subject: "Bayram kunlarida navbatchilik jadvali",
      category: "schedule",
      person: "HR Admin",
      department: "Kadrlar bo'limi",
      responsible: "HR Direktor",
      status: "progress",
      description: "Dekabr bayramlari uchun navbatchilik ro'yxati.",
      history: [{ at: "02.11.2024 09:30", text: "Jarayonda", by: "HR Admin" }],
      comments: [],
    },
  ],
};

export function NBuyruqlarPage() {
  return <OrdersJournalPage config={CONFIG} />;
}
