import { OrdersJournalPage, type OrdersJournalConfig } from "../components/OrdersJournalPage";

const CONFIG: OrdersJournalConfig = {
  kind: "P",
  title: "P-buyruqlar",
  subtitle: "Kadrlar bo'yicha buyruqlar (xodimlar, lavozimlar, ta'til, mukofot, intizomiy va boshqalar)",
  path: "/journals/p-buyruqlar",
  newLabel: "Yangi P-buyruq",
  categories: {
    appoint: { label: "Lavozimga tayinlash", bg: "bg-[#e8f1ff]", text: "text-[#1b5ef3]" },
    leave: { label: "Ta'til", bg: "bg-[#fce7f3]", text: "text-[#be185d]" },
    reward: { label: "Rag'batlantirish", bg: "bg-[#fff4e6]", text: "text-[#c2410c]" },
    terminate: { label: "Ishdan bo'shatish", bg: "bg-[#fee2e2]", text: "text-[#dc2626]" },
    transfer: { label: "O'tkazish", bg: "bg-[#f3e8ff]", text: "text-[#7c3aed]" },
    other: { label: "Boshqa", bg: "bg-slate-100", text: "text-slate-600" },
  },
  stats: {
    total: 186,
    done: 142,
    donePct: "76.3%",
    progress: 28,
    progressPct: "15.1%",
    cancelled: 6,
    cancelledPct: "3.2%",
    month: 14,
    monthDelta: 5,
    totalDelta: 12,
    archive: 312,
  },
  seed: [
    {
      id: "p1",
      number: "P-000124",
      date: "2025-01-12",
      subject: "Aliyev Behruzni lavozimga tayinlash to'g'risida",
      category: "appoint",
      person: "Aliyev Behruz",
      department: "IT bo'limi",
      responsible: "HR Admin",
      status: "done",
      description: "Aliyev Behruz Alisherovichni 2025-yil 15-yanvardan IT bo'limi yetakchi dasturchisi lavozimiga tayinlash.",
      history: [
        { at: "10.01.2025 09:40", text: "Buyruq yaratildi", by: "HR Admin" },
        { at: "12.01.2025 14:20", text: "Ijro etildi", by: "Rektor" },
      ],
      comments: [
        { at: "11.01.2025", by: "IT boshliq", text: "Lavozim stavkasi tasdiqlandi." },
        { at: "12.01.2025", by: "HR Admin", text: "Shaxsiy ish varag'iga yozildi." },
        { at: "12.01.2025", by: "Aliyev B.", text: "Buyruq bilan tanishdim." },
      ],
    },
    {
      id: "p2",
      number: "P-000123",
      date: "2025-01-10",
      subject: "Karimova Dilnozaga mehnat ta'tili berish haqida",
      category: "leave",
      person: "Karimova Dilnoza",
      department: "Kadrlar bo'limi",
      responsible: "HR Direktor",
      status: "progress",
      description: "2025-yil 20-yanvardan 10-fevralgacha yillik mehnat ta'tili.",
      history: [{ at: "10.01.2025 11:00", text: "Jarayonda", by: "HR Direktor" }],
      comments: [{ at: "10.01.2025", by: "HR Direktor", text: "Imzo kutilyapti." }],
    },
    {
      id: "p3",
      number: "P-000122",
      date: "2025-01-08",
      subject: "Yusupova Nilufarni rag'batlantirish to'g'risida",
      category: "reward",
      person: "Yusupova Nilufar",
      department: "Iqtisodiyot fakulteti",
      responsible: "Dekan",
      status: "done",
      description: "Ilmiy natijalar uchun bir martalik mukofot to'lash.",
      history: [{ at: "08.01.2025 16:00", text: "Ijro etildi", by: "Rektor" }],
      comments: [],
    },
    {
      id: "p4",
      number: "P-000121",
      date: "2025-01-05",
      subject: "Toshmatov Bekzodni ishdan bo'shatish haqida",
      category: "terminate",
      person: "Toshmatov Bekzod",
      department: "Marketing bo'limi",
      responsible: "HR Admin",
      status: "cancelled",
      description: "O'z xohishi bilan ishdan bo'shash arizasi asosida — keyinchalik bekor qilindi.",
      history: [
        { at: "03.01.2025 10:00", text: "Buyruq yaratildi", by: "HR Admin" },
        { at: "05.01.2025 15:30", text: "Bekor qilindi", by: "HR Direktor" },
      ],
      comments: [{ at: "05.01.2025", by: "HR Direktor", text: "Xodim arizasini qaytarib oldi." }],
    },
    {
      id: "p5",
      number: "P-000120",
      date: "2024-12-28",
      subject: "Rahimova Dilnozani boshqa lavozimga o'tkazish",
      category: "transfer",
      person: "Rahimova Dilnoza",
      department: "Xalqaro aloqalar",
      responsible: "Prorektor",
      status: "done",
      description: "Mutaxassisdan bo'lim mudiri o'rinbosariga o'tkazish.",
      history: [{ at: "28.12.2024 12:00", text: "Ijro etildi", by: "Rektor" }],
      comments: [],
    },
    {
      id: "p6",
      number: "P-000119",
      date: "2024-12-20",
      subject: "Ismoilova Malikaga ta'til berish haqida",
      category: "leave",
      person: "Ismoilova Malika",
      department: "Ingliz tili kafedrasi",
      responsible: "HR Admin",
      status: "progress",
      description: "O'z hisobidan ta'til — 5 ish kuni.",
      history: [{ at: "20.12.2024 09:15", text: "Jarayonda", by: "HR Admin" }],
      comments: [],
    },
    {
      id: "p7",
      number: "P-000118",
      date: "2024-12-15",
      subject: "Ergashev Javloni lavozimga tayinlash to'g'risida",
      category: "appoint",
      person: "Ergashev Javlon",
      department: "Xalqaro aloqalar",
      responsible: "HR Direktor",
      status: "done",
      description: "Xalqaro aloqalar bo'limi katta mutaxassisi lavozimiga tayinlash.",
      history: [{ at: "15.12.2024 11:40", text: "Ijro etildi", by: "Rektor" }],
      comments: [{ at: "15.12.2024", by: "HR Direktor", text: "Yangi lavozim tavsifi biriktirildi." }],
    },
    {
      id: "p8",
      number: "P-000117",
      date: "2024-12-01",
      subject: "Nazarova Kamolani rag'batlantirish to'g'risida",
      category: "reward",
      person: "Nazarova Kamola",
      department: "Marketing bo'limi",
      responsible: "HR Admin",
      status: "done",
      description: "Yil yakuni bo'yicha eng yaxshi natija uchun mukofot.",
      history: [{ at: "01.12.2024 10:00", text: "Ijro etildi", by: "Rektor" }],
      comments: [],
    },
    {
      id: "p9",
      number: "P-000116",
      date: "2024-11-22",
      subject: "Qosimov Sardorni ishdan bo'shatish haqida",
      category: "terminate",
      person: "Qosimov Sardor",
      department: "Moliya bo'limi",
      responsible: "HR Direktor",
      status: "done",
      description: "Mehnat shartnomasi muddati tugashi munosabati bilan.",
      history: [{ at: "22.11.2024 15:00", text: "Ijro etildi", by: "Rektor" }],
      comments: [],
    },
    {
      id: "p10",
      number: "P-000115",
      date: "2024-11-10",
      subject: "Abdullayeva Sevaraga ta'til berish haqida",
      category: "leave",
      person: "Abdullayeva Sevara",
      department: "Agronomiya fakulteti",
      responsible: "HR Admin",
      status: "progress",
      description: "Yillik mehnat ta'tili — 14 kalendar kun.",
      history: [{ at: "10.11.2024 09:00", text: "Jarayonda", by: "HR Admin" }],
      comments: [],
    },
  ],
};

export function PBuyruqlarPage() {
  return <OrdersJournalPage config={CONFIG} />;
}
